# Generated by Django 4.2.5 on 2023-09-20 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_people_you_may_know_user_info_you_might_like_skills_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='people_you_may_know',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.user_info'),
        ),
        migrations.AddField(
            model_name='you_might_like',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.user_info'),
        ),
    ]
